name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Action tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://Hangghost:$HF@huggingface.co/spaces/Hangghost/demo-MLOps
      - name: Push to Hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://Hangghost:$HF@huggingface.co/spaces/Hangghost/demo-MLOps main
      
